bookrecom/book/urls.py
from django.urls import path
from .views import recommend_books
from book.views import index

urlpatterns = [

    path('',index,name='index')
]

bookrecom/bookrecom/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('book.urls'))
]

bookrecom/book/models.py
from django.db import models

class Book(models.Model):
    
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    description = models.TextField()


    def __str__(self) :
        return self.title

bookrecom/book/forms.py
from django import forms


class Booksearchform(forms.Form):
    book_title = forms.CharField( max_length=200  , required=False)
  
   

bookrecom/book/views.py
from django.shortcuts import render
import pandas as pd
from . models import Book
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
from .forms import Booksearchform

def loadbooks(BooksDataset):
 df= pd.read_csv(BooksDataset)
 return df


def creatbook():
    book_df =loadbooks('BooksDataset.csv')   

    for _, row in book_df . iterrows():
        Book.objects.get_or_create(title=row['Title'], author=row['Authors'], description=['Description']) 





# تابع برای ایجاد ماتریس TF-IDF
def create_tfidf_matrix():
    books = Book.objects.all()  # دریافت تمامی کتابها
    titles = [book.title for book in books]  # استخراج عناوین کتابها
    tfidf_vectorizer = TfidfVectorizer()  # ایجاد مدل وکتورایز
    tfidf_matrix = tfidf_vectorizer.fit_transform(titles)  # وکتورایز کردن عناوین
    return tfidf_matrix, tfidf_vectorizer  # 



# تابع برای ایجاد مدل KNN
def create_knn_model(tfidf_matrix):
    knn = NearestNeighbors(n_neighbors=3, metric='cosine')  # تنظیم تعداد همسایگان
    knn.fit(tfidf_matrix)  # آموزش مدل KNN بر روی ماتریس TF-IDF
    return knn 




def recommend_books(book_title):
    print(f"book:{book_title}")
    books = Book.objects.all()  # دریافت تمامی کتابها

    tfidf_matrix, tfidf_vectorizer = create_tfidf_matrix()  # ایجاد ماتریس TF-IDF
    knn_model = create_knn_model(tfidf_matrix)  # ایجاد مدل KNN

    try:
        # پیدا کردن ایندکس کتاب ورودی
        idx = next(i for i, book in enumerate(books) if book.title == book_title)
        distances, indices = knn_model.kneighbors(tfidf_matrix[idx], n_neighbors=7)  # پیدا کردن همسایگان نزدیک

        recommended_books = []
        for i in indices.flatten():
            recommended_books.append(books[int(i)])  # اضافه کردن کتابهای پیشنهادی به لیست
    
        return recommended_books  # بازگرداندن لیست کتابهای پیشنهادی
    except StopIteration:
        return None  




def index(request):
    form = Booksearchform()
    recommendations = []

    if request.method == 'POST':
        form = Booksearchform(request.POST)
        if form.is_valid():
            print("form is valid")
            book_title = form.cleaned_data['book_title'].strip()
            print(f"book title submited:{book_title}")
            recommendations = recommend_books(book_title)
            print(f"recommention returned : {recommendations}")

    return render(request, 'book/index.html', {'form': form, 'recommendations': recommendations})

     

bookrecom/book/templates/book/index.html
<!-- recommendations/templates/recommendations/index.html -->

<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Recommendations</title>
   
</head>
<style>


body{
    margin: 0;
    padding: 0;
    background: rgba(46, 154, 243, 0.584);
}


    .container{
        
        display: flex;
        justify-content:center ;
        align-items: center;
        flex-direction: column;
        width: 100%;
        height: 100%;

    }

    button{
        width: 100%;
        height: 100%;
        border-radius: 50px;
        background-color: rgb(232, 96, 22);
        border: none;
        font-weight: bolder;
        transition-duration: 0.5s;

    }
    button:hover{
        background-color: beige;

    }

    #id_book_title{
        border: none;
        border-radius: 5px;
        height: 30px;
        width: 200px;
        background-color: rgba(255, 255, 255, 0.765);

    }

    label{
        font-size: large;
        font-weight: bold;


    }

    ul{
        border: 0.1px solid rgba(213, 211, 211, 0.347);
        padding: 10px;
    }

 li{
      list-style: none;
      padding: 10px;
     border: 0.1px solid rgba(217, 17, 217, 0.347);
     margin-top: 30px;
 }
</style>
<body>
    <div class="container">
        <h2>Welcome to the book recommendation system</h2>
        <form method="post">

            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">click</button>
            
        </form>

        {% if recommendations %}
            <h3>Suggested books:</h3>
            <ul>
            {% for book in recommendations %}
                <li>{{ book.title }} - {{ book.author }}</li>
                
            
            {% endfor %}
            </ul>
            {% else %}
                <li>No book found, database is not complate but for example you can try The Missing Person to see how system work.</li>
        {% endif %}
    </div>
</body>
</html>